### ISSUE TITLE
Array Typing 

### ISSUE THREAD

**Issue by vandenesseml** [retejs/rete#310]
I have come across an issue in engine/component and engine/index.

node_modules/rete/types/engine/component.d.ts(11,58): error TS2370: A rest parameter must be of an array type.?

node_modules/rete/types/engine/index.d.ts(36,14): error TS1122: A tuple type element list cannot be empty.?

node_modules/rete/types/engine/index.d.ts(36,5): error TS2370: A rest parameter must be of an array type.?

component.ts
worker parameter needs to be any[]
abstract worker(node: NodeData, inputs: WorkerInputs, outputs: WorkerOutputs, ...args: any **\[\]** ): any;

index.ts:
process parameter needs to be typed:
process(data: Data, startId?: number | string | null, ...args: **any**[]): Promise<"success" | "aborted">;

**Comment by Ni55aN** [comment]
Please check `v1.3.1-rc.2`
```js
export type WorkerArgs = [number];
```

```js
await engine.process<WorkerArgs>(editor.toJSON(), 1, 456);
```

```js
worker(node: NodeData, inputs: WorkerInputs, outputs, ...args: WorkerArgs) {
```

**Comment by damiano-sca** [comment]
Hi,
I have encountered the same errors. After updating to v1.3.1-rc.3 the only one remaining is this one:

ERROR in node_modules/rete/types/engine/index.d.ts(33,76): error TS2370: A rest parameter must be of an array type.

referring to this line in the 'Engine' class declaration: 

process<T extends any[]>(data: Data, startId?: number | string | null, ...args: T): Promise<"success" | "aborted">;

**Comment by Ni55aN** [comment]
@damiano-sca what is your  line of code  and TS version? I cant reproduce it in Angular project

**Comment by damiano-sca** [comment]
I simply ran the application with "ng serve", with @angular/cli@6.2.8 and TS version 2.9.2.
I'll try to migrate to the latest Angular and TS and see if the problem persists

**Comment by damiano-sca** [comment]
As an update, I ran the application with @angular/cli@8.0.1 and TS 3.4.2 and everything worked
